### PR TITLE
add content state feature

### PR DESCRIPTION
**Pull request by otacke**
Implements feature for saving and restoring the user's text input.

### CODE REVIEW

**Comment by otacke** [comment]
I just had an additional idea. I guess it was nice for the user if there was an indicator if his/her latest text has already been saved by the interval save feature. I might add that.

**Comment by otacke** [comment]
Please note that this pull request will conflict with https://github.com/h5p/h5p-text-input-field/pull/7 If you want to merge with both, I can provide you with a new pull request from my [essay_mix branch](https://github.com/otacke/h5p-text-input-field/tree/essay_mix) where both are combined.

**Comment by timothyylim** [comment]
Hi @otacke, it makes more sense to be targeted with pull requests instead of mixing two into one. Do you think you could fix the conflicts in this one so that I can test and merge it in?

**Comment by otacke** [comment]
Sure, I'll fix that. What's the best option if you have multiple changes (that's why I created separated pull requests for being accepted or rejected individually) that may create conflicts if you apply all of them because in that case they may require some different handling?

**Comment by timothyylim** [comment]
@otacke , I don't have a good answer for that. I would try to develop them one at a time keep the maintainer informed.

**Comment by otacke** [comment]
@timothyylim Sorry that the changes took so long. I am quite busy right now ...

**Comment by timothyylim** [comment]
Hi @otacke, thanks for taking the time to fix the conflicts. I just have one more question, when exactly does the state get saved? I can't seem to trigger it manually.

**Comment by otacke** [comment]
@timothyylim You will need to activate the "save content state" feature in H5P's host system. H5P will then trigger getCurrentState() in regular intervals and on some xAPI statements. https://h5p.org/node/106535

**Comment by timothyylim** [comment]
Ok, I was under the impression that it was triggered internally for some reason. I've tested this and it works well with h5p-essay. Good job, @otacke !

**Comment by otacke** [comment]
@timothyylim Essay uses its own implementation of an input field, because I didn't know if and when the new features might make it, and because some things are limited when including a library in semantics -- and the Essay version is even a little more advanced. Both are very similar though. I could send you a tiny text-input-field test content type if you'd like to have it.

**Comment by timothyylim** [comment]
Yep, if you could do that it would be great. Just send it to my email.

**Comment by timothyylim** [comment]
@otacke , I think it would be better if the functions you added to the prototype (getCurrentState, setState and updateMessageSaved) were placed in h5p-essay instead so that the parent content type can decide for itself whether to display a message once the content is saved. This should be done in another pull request. Any thoughts?

**Comment by otacke** [comment]
@timothyylim Not thought ones -- too busy :-/ I put it in text-input-field because I think that user's should _always_ know when it's safe to leave the page. Longer texts as in Essay might not be written in one sweep, and the same might be true for Documentation Tool if people regularly document progress, etc.).

**Comment by fnoks** [comment]
@otacke and @timothyylim, here's my two cents:

getCurrentState and setState should be implemented in text-input-field, but the updateMessageSaved should be moved to h5p-essay.

Imagine a Documentation Tool including 10 input fields on a page. This pull request would then make 10 "Saved" messages appear when getCurrentState is invoked. I don't think that is wanted behavior. It should be up to the parent to decide if a message should be displayed, and how it should look/where it should be placed.

Does this sound reasonable to you guys?

**Comment by timothyylim** [comment]
@fnoks , I agree with that.

**Comment by otacke** [comment]
Sorry for the late reply. In Germany it's "conference season" in the higher education scene, two projects keep me pretty busy, ...

I'll gladly make the changes as proposed. Should I keep the position/code for the saved message as an option in case the parent content types wants to use it instead if coming up with a separate solution?

**Comment by fnoks** [comment]
I think the best is to keep the text-input-field as clean as possible. I.e: remove the "saveMessag" completely, and move it to the parent. In this case to H5P.Essay's getCurrentState().

**Comment by otacke** [comment]
I'll remove the function from text-input-field this weekend.

**Pull request merged**
