### PR TITLE
add option for maximum text length

### PR DESCRIPTION
**Pull request by otacke**
A teacher may require to limit the number of characters for an input field, e.g. for an essay. This pull request adds the appropriate optional setting to the editor. If a number is given, a dynamic message will display the number of characters that the student has left below the input field. The message can be altered by the teacher including a variable for the number of characters left.

### CODE REVIEW

**Comment by timothyylim** [comment]
Nice, @otacke. I've made an issue for this to be reviewed and merged in the next release:
https://h5ptechnology.atlassian.net/browse/HFP-1380

**Comment by otacke** [comment]
Thanks. Maybe Jelena can have a look at it, too. The Look&Feel/CSS could possibly be enhanced.

**Comment by otacke** [comment]
Oh, what a nifty tool! Do you intend to use double quotes for strings as default?

**Comment by timothyylim** [comment]
Yes, this was set up recently. I think double quotes will be the standard.

**Comment by otacke** [comment]
Should I change the code right now?

**Comment by fnoks** [comment]
@otacke : I was testing out a new tool, but was not aware it pushed things to github :( Please ignore for now, since it is not correctly setup in regards to our coding standard.

Note: We use single quotes :)

**Comment by otacke** [comment]
Sorry, I screwed up some git stuff. The new request is https://github.com/h5p/h5p-text-input-field/pull/7

**Pull request closed without merging**
